import {
  AppWindow,
  Archive,
  Calculator,
  CalendarDays,
  ClipboardList,
  FileSearch,
  Globe,
  Keyboard,
  Languages,
  Link2,
  MessagesSquare,
  NotebookPen,
  Puzzle,
  Search,
  Smile,
  Sparkles,
  SquareTerminal,
  Sun,
  Tag,
  Trash2,
  WandSparkles,
  LayoutGrid,
  Zap,
  type LucideIcon,
} from "lucide-react";

// Generic glyphs come from lucide-react. Feature cards reference these by
// name from the data folder; everything else imports lucide directly.
export const featureIcons = {
  launch: Search,
  extensions: Puzzle,
  calculator: Calculator,
  clipboard: ClipboardList,
  snippets: SquareTerminal,
  notes: NotebookPen,
  fileSearch: FileSearch,
  quicklinks: Link2,
  windows: LayoutGrid,
  emoji: Smile,
  globe: Globe,
  bolt: Zap,
  hyper: Sparkles,
  backup: Archive,
  alias: Tag,
  uninstall: Trash2,
  inputSource: Languages,
  appearance: Sun,
  keyboard: Keyboard,
  aiChat: MessagesSquare,
  quickActions: WandSparkles,
  calendar: CalendarDays,
  navigation: AppWindow,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof featureIcons;
